version: '3.9'

services:

  # --- FRONT-END --- #
  frontend:
    build:
      # TODO rename fontend -> frontend
      context: ./fontend
      # TODO rename fontend -> frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: npm start
    env_file:
      - ./fontend/.env.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # --- BACK-END --- #
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: java -jar /app.jar
    depends_on:
      - backend-db
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"

  backend-db:
    image: postgres:latest
    container_name: backend-db
    env_file:
      - ./backend/.env.prod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- CORE --- #
  core:
    container_name: core
    build:
      context: ./core
      dockerfile: Dockerfile
    restart: no
    command: sh -c "PYTHONPATH=src uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - ./core/.env.prod
    depends_on:
      - core-vector-database
      - core-chats-db
  
  core-setup:
    container_name: core-setup
    build:
      context: ./core
      dockerfile: Dockerfile
    restart: no
    command: sh -c "PYTHONPATH=src python -m src.data_setup"
    env_file:
      - ./core/.env.prod
    depends_on:
      - core-vector-database

  core-vector-database:
    image: qdrant/qdrant:latest
    restart: no
    container_name: core-vector-database
    ports:
      - 6333:6333
    expose:
      - 6333
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  core-chats-db:
    image: mongo:latest
    container_name: core-chats-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  pgdata:
  mongo-data: