version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: java -jar /app.jar
    depends_on:
      - backend-db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "8080:8080"

  backend-db:
    image: postgres:latest
    container_name: products_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"




#version: '3.9'
#
#services:
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    command: java -jar /app.jar
#    depends_on:
#     - backend-db
#    environment:
#     - SPRING_DATASOURCE_URL=jdbc:postgresql://products_db:5432/backend-db
#     - SPRING_DATASOURCE_USERNAME=postgres
#     - SPRING_DATASOURCE_PASSWORD=postgres123
#     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - "8080:8080"
#
#  backend-db:
#   image: postgres:latest
#   container_name: products_db
#   environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=postgres123
#     - POSTGRES_DB=products
#   ports:
#     - "5432:5432"