version: '3.8'

services:
  core:
    container_name: core
    build: .
    restart: no
    command: sh -c "PYTHONPATH=src uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - ./src/.env.prod
    depends_on:
      - core-setup
  
  core-setup:
    container_name: core-setup
    build: .
    restart: no
    command: sh -c "PYTHONPATH=src python -m src.data_setup"
    depends_on:
      - core-vector-database

  core-vector-database:
    image: qdrant/qdrant:latest
    restart: no
    container_name: core-vector-database
    ports:
      - 6333:6333
    expose:
      - 6333
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO      